version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building and preparing deployment package..."
      - mkdir -p output
      - cp -r index.html appspec.yml scripts/ output/
      - chmod +x output/scripts/*.sh
artifacts:
  base-directory: output
  files:
    - '**/*'
