version: 0.2

phases:
  install:
    commands:
      - echo "Install phase (no additional packages required)"

  build:
    commands:
      - echo "Packaging application files..."
      - rm -rf output || true
      - mkdir -p output
      - cp -r index.html appspec.yml scripts/ output/ || true
      - cd output
      - zip -r ../app-deploy.zip ./*
      - cd ..

artifacts:
  files:
    - app-deploy.zip
